spring:
  application:
    name: customer
  datasource:
    username: 'root'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/customer
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

server:
  port: 8080

