server:
  port: 8081

spring:
  application:
    name: fraud
  data:
    mongodb:
      uri: mongodb://localhost:27018/fraud
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
